#182201663 Integrate Coveralls code coverage service
atlp-rwanda/bravo-bn-be pull request #12
Opened 2022-05-24 18:08 UTC by uwambajeddy

####What does this PR do?
This PR is used to analyse the project's code quality. 

####Description of Task to be completed?
-Adding coveralls service to the project

####How should this be manually tested?
after cloning this PR , cd into it Run npm install then npm run coverage

####What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201663

2022-05-26 05:33 UTC, alaintresor submitted a review, later dismissed

2022-05-26 08:42 UTC, didasmbalanya requested changes

2022-05-26 08:42 UTC, didasmbalanya commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/atlp-rwanda/bravo-bn-be/badge.svg?branch=ch-code-coverage-182201663)](https://coveralls.io/github/atlp-rwanda/bravo-bn-be?branch=ch-code-coverage
Wrong branch. set it to show coverage on develop

2022-05-26 11:19 UTC, joshwambere reviewed
@uwambajeddy  can add the badges

2022-05-26 11:24 UTC, uwambajeddy commented
> @uwambajeddy can add the badges

@joshwambere Mr Didas told me to put the coverage badge to the "develop branch" earlier. But I don't have access to the develop branch to make any changes.

2022-05-26 11:54 UTC, joshwambere commented
> > @uwambajeddy can add the badges
> 
> @joshwambere Mr Didas told me to put the coverage badge to the "develop branch" earlier. But I don't have access to the develop branch to make any changes.

since your branch will be merged into develop, it makes sense to add into your PR, cause there is no way you'll be making changes into develop directly

2022-05-30 07:40 UTC, joshwambere approved these changes, later dismissed

2022-05-30 09:52 UTC, Patricknshimiyimana approved these changes, later dismissed

2022-05-30 13:12 UTC, Placide123 submitted a review, later dismissed

2022-05-30 13:16 UTC, mwisemarierose approved these changes, later dismissed

2022-05-31 16:51 UTC, joshwambere approved these changes

2022-05-31 16:52 UTC, merged