Ft registration 182201715
atlp-rwanda/bravo-bn-be pull request #15
Opened 2022-05-26 11:18 UTC by uwambajeddy

#### What does this PR do?
This is a user registration PR 

#### Description of Task to be completed?
- creating registration endpoint
- authentication controller

#### How should this be manually tested?
After running the app with "npm run start:dev" use this endpoint "/api/v1/signup" on a POST request to register a user.

https://www.pivotaltracker.com/story/show/182201715

2022-05-26 15:07 UTC, didasmbalanya requested changes
Missing tests

2022-05-29 19:03 UTC, joshwambere commented on src/controllers/authentication.js
> +    createSendToken(currentUser, 201, res);
status should be 200

2022-06-01 15:29 UTC, Patricknshimiyimana commented
Hey man, This branch has conflicts that must be resolved

2022-06-02 06:57 UTC, uwambajeddy commented
> 

yes, we are merging PRs, we get on this one I will

2022-06-04 18:16 UTC, alaintresor approved these changes, later dismissed

2022-06-04 19:32 UTC, Placide123 approved these changes, later dismissed

2022-06-05 21:37 UTC, joshwambere requested changes

2022-06-05 21:37 UTC, joshwambere commented on src/controllers/authentication.js
> +            new AppError('The user belonging to this token does no longer exist', 401)
may be a user friendly message, would be great

2022-06-05 21:37 UTC, joshwambere commented on src/helpers/validation_schema.js
> +    phoneNumber: Joi.number(),
the size of the number is crucial here

2022-06-06 17:06 UTC, joshwambere approved these changes

2022-06-06 17:11 UTC, merged