Ft login user via email and password 182201718
atlp-rwanda/bravo-bn-be pull request #17
Opened 2022-05-28 07:36 UTC by alaintresor

#### What does this PR do?
- add user login functionality via email and password
- add swagger documentation for this endpoint

#### Description of Task to be completed?
-user sign up functionality

#### How should this be manually tested?
after clone it, cd into it and run npm install, npm run start:dev and open any web browser type in this UR "localhost:['YOUR_PORT']/api/v1/docs/" and then your found user route

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201718

![Screenshot (30)](https://user-images.githubusercontent.com/55650162/170815563-0c67aa00-8b98-45c4-b110-40ff720cef0f.png)
![Screenshot (31)](https://user-images.githubusercontent.com/55650162/170815588-540def9e-8b59-49e8-8d57-175c47b1f5a8.png)

2022-05-28 07:39 UTC, Placide123 approved these changes, later dismissed

2022-05-29 15:37 UTC, Patricknshimiyimana commented
This branch has conflicts that must be resolved

2022-05-30 07:51 UTC, joshwambere requested changes
and also write tests for you endpoint

2022-05-30 07:51 UTC, joshwambere commented on src/services/user.service.js
> +export const loginUser= async (req, res) => {
Please move this codes into Authentication controller as registration is in authentication controller

2022-05-30 07:51 UTC, joshwambere commented on src/services/user.service.js
> +		return res.status(200).json({
where do you compare the provided password and the actual password in DB

2022-05-31 16:46 UTC, alaintresor commented
![Screenshot (32)](https://user-images.githubusercontent.com/55650162/171228997-97d9244a-3528-455f-b639-6970973df409.png)

2022-06-05 17:56 UTC, uwambajeddy commented on .env.example
> -PROD_PGDATABASE=YOUR_POSTGRES_PROD_DATABASE
It wasn't necessary to

2022-06-05 17:56 UTC, uwambajeddy commented on README.md
> +# bravo-bn-be
Bro you removed the coverage badge

2022-06-05 17:57 UTC, uwambajeddy commented on package.json
> -    "prepare": "husky install"
you removed this command

2022-06-05 17:58 UTC, uwambajeddy commented on src/controllers/error.js
> -import AppError from '../utils/appError';
leave this code as it is.

2022-06-05 17:59 UTC, uwambajeddy commented on src/database/models/user.js
> -    passwordResetExpires: DataTypes.DATE,
but whyyyy?

2022-06-06 19:25 UTC, joshwambere requested changes

2022-06-06 19:25 UTC, joshwambere commented on src/migrations/20220523191126-create-users.js
> +'use strict';
migrations folder should be in Database folder

2022-06-06 19:25 UTC, joshwambere commented on src/services/user.service.js
> +	// try{
same with seeders

2022-06-06 19:25 UTC, joshwambere commented on src/controllers/error.js
> +import AppError from '../utils/AppError';
imports error here

2022-06-07 13:37 UTC, Placide123 approved these changes, later dismissed

2022-06-08 06:35 UTC, Patricknshimiyimana approved these changes

2022-06-08 09:17 UTC, Placide123 approved these changes

2022-06-08 14:34 UTC, uwambajeddy approved these changes

2022-06-09 08:35 UTC, merged