feature(google-facebook-auth): A user can login in to Barefoot application via Facebook and Google
atlp-rwanda/bravo-bn-be pull request #19
Opened 2022-05-29 08:54 UTC by uwambajeddy

#### What does this PR do?
This PR helps the user to login the application using Google or facebook.

#### How should this be manually tested?
- `GET` `/api/v1/user/auth/google` for google authentication 
- `GET` `/api/v1/user/auth/facebook` for facebook authentication 

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201719

2022-06-05 17:17 UTC, mwisemarierose approved these changes, later dismissed

2022-06-05 17:19 UTC, alaintresor approved these changes, later dismissed

2022-06-06 19:40 UTC, joshwambere requested changes

2022-06-06 19:40 UTC, joshwambere commented on src/controllers/authentication.js
> +import {Op} from'Sequelize';
imports error here `sequelize` instead of `Sequelize`

2022-06-13 08:36 UTC, merged