ft(send-mail): send email on user registration
atlp-rwanda/bravo-bn-be pull request #22
Opened 2022-05-30 12:37 UTC by mwisemarierose

####What does this PR do?
this PR send email to the successfully registered user .
 User should be able to receive a verification link via email upon successful signup

####what are the relevant pivotal tracker stories?
 Send to a user upon successful registration.
#182201716

2022-05-30 12:50 UTC, uwambajeddy approved these changes, later dismissed
LGTM

2022-06-08 09:22 UTC, joshwambere reviewed
why do you have two authentication.js controllers in controllers folder

2022-06-14 08:54 UTC, joshwambere requested changes

2022-06-14 08:54 UTC, joshwambere commented on docker-compose.yml
> +<<<<<<< HEAD
do proper rebase

2022-06-14 08:54 UTC, joshwambere commented on test/authentication.test.js
> +    // it('Should return 201', (done) => {
please don't comment codes you did not write

2022-06-14 08:54 UTC, joshwambere commented on test/authentication.test.js
> +    // it("Should login user", (done) => {
un-comment these tests please

2022-06-14 08:54 UTC, joshwambere commented on test/roles.test.js
> +  /* it('It should update the user role', (done) => {
un-comment this too

2022-06-21 09:32 UTC, didasmbalanya requested changes
Where is the endpoint that takes the user token when they click and verifies the user in the DB?

2022-06-21 09:32 UTC, didasmbalanya commented on .env.example
missing 'EMAIL_FROM`

2022-06-21 09:32 UTC, didasmbalanya commented on src/utils/email.js
> +    this.from = `Barefoot Nomad <${process.env.EMAIL_FROM}>`;
Add EMAIL_FROM to the env.sample

2022-06-21 09:32 UTC, didasmbalanya commented on src/controllers/authentication.js
> +}
add empty line at the end

2022-06-21 09:32 UTC, didasmbalanya commented on src/views/email/welcome.ejs
> +</html>
add empty line at the end

2022-06-21 09:32 UTC, didasmbalanya commented on test/authentication.test.js
> +  });
add empty line at the end

2022-06-21 09:32 UTC, didasmbalanya commented on test/roles.test.js
> -});
add empty line at the end

2022-06-24 06:46 UTC, uwambajeddy approved these changes, later dismissed

2022-06-28 07:14 UTC, merged