Ft profile page settings
atlp-rwanda/bravo-bn-be pull request #26
Opened 2022-06-02 05:02 UTC by alaintresor

#### What does this PR do?
updating user profile(user model)

#### Description of Task to be completed?
-get user profile by user-id
-update user profile

#### How should this be manually tested?
After running the app with` npm run start:dev` use this endpoint` /api/v1/user/update/[USER ID]` on a POST request to update a user profile.
`GET /api/v1/user/` to view inserted user and `GET /api/v1/user/[USER ID]` to view a user profile by id
**OR**
after starting server, you can open any web browser and put this URL`'localhost:[YOUR PORT]/api/v1/docs'` to test it with swagger

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201721

![Screenshot (34)](https://user-images.githubusercontent.com/55650162/171555904-c99b2fb3-378e-461d-9786-93ef25bfde3d.png)

![Screenshot (33)](https://user-images.githubusercontent.com/55650162/171555963-f229dd29-74a0-45bf-a9af-dd50cd6b4906.png)

2022-06-02 06:45 UTC, uwambajeddy reviewed
This looks damn good to me, but I was wondering if we're not supposed to add tests.

2022-06-03 13:03 UTC, Placide123 requested changes
hi, try to use `put` or `patch` instead of using `post`.  because it is the one which performs the update. thank you. at `userRouter.post('/update/:id',protect,updateUserProfile);`

2022-06-04 19:34 UTC, Placide123 approved these changes, later dismissed

2022-06-05 18:03 UTC, uwambajeddy reviewed
You made mistakes in code rebase that can affect the app to crush

2022-06-06 09:01 UTC, uwambajeddy submitted a review, later dismissed

2022-06-08 22:03 UTC, closed without merging