feature Reject/Approve Trip Request 182201726
atlp-rwanda/bravo-bn-be pull request #42
Opened 2022-06-13 11:37 UTC by alaintresor

#### What does this PR do?
Approve /Reject Trip Request
#### Description of Task to be completed?

- Approve trip request by manager
- Reject trip request by manager
- View all trip request

#### How should this be manually tested?
After running the app with `npm run start:dev` and **login as manager** and after using this endpoint `/api/v1/trip-request/approve/[TRIP-REQUEST ID]` on a PUT request to Approve trip request or using this endpoint `/api/v1/trip-request/reject/[TRIP-REQUEST ID]` on a PUT request to Reject a trip request.
`GET/api/v1/trip-request/` to view all trip requests
OR
after starting a server, you can open any web browser and put this URL'localhost:[YOUR PORT]/api/v1/docs' to test it with swagger

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201726

2022-06-15 09:22 UTC, uwambajeddy approved these changes, later dismissed
LGTM

2022-06-16 01:00 UTC, joshwambere commented on test/tripRequest.test.js
> +                    expect(res.status).to.equal(200);
you might want tto also test the right message is being deliverd

2022-06-16 01:01 UTC, joshwambere commented
and solve some conflicts on this PR

2022-06-21 13:03 UTC, joshwambere submitted a review, later dismissed
LGTM

2022-07-13 09:25 UTC, uwambajeddy submitted a review, later dismissed

2022-07-13 14:14 UTC, Placide123 approved these changes, later dismissed

2022-07-13 14:55 UTC, mwisemarierose approved these changes, later dismissed

2022-07-13 15:22 UTC, Patricknshimiyimana submitted a review, later dismissed

2022-07-14 09:03 UTC, joshwambere requested changes

2022-07-14 09:03 UTC, joshwambere commented on src/controllers/tripRequest.js
> +
why do you have two trip request controllers?

2022-07-14 20:50 UTC, closed without merging