#182201736 feature(mark-notifications): Users should be able to mark all notifications as read
atlp-rwanda/bravo-bn-be pull request #43
Opened 2022-06-15 14:01 UTC by uwambajeddy

#### What does this PR do?
This PR allows the user to make a request to visit multiple destinations within the same travel request

#### How should this be manually tested?
- `GET` `/api/v1/user/notification` for getting all notifications
- `GET` `/api/v1/user/notification/read` mark them as read
- `GET` `/api/v1/user/notification/{id}` for getting individual notification

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201736

2022-06-17 10:15 UTC, alaintresor approved these changes, later dismissed

2022-06-17 13:18 UTC, mwisemarierose submitted a review, later dismissed

2022-06-20 14:12 UTC, Patricknshimiyimana submitted a review, later dismissed

2022-06-21 12:43 UTC, joshwambere requested changes

2022-06-21 12:43 UTC, joshwambere commented on src/controllers/notificationController.js
> +const Notifications = db['Notifications'];
don't you think creating notification should be in services so it can be used across the system easily

2022-06-21 12:45 UTC, uwambajeddy commented on src/controllers/notificationController.js
> +const Notifications = db['Notifications'];
Good approach.

2022-06-23 10:57 UTC, joshwambere approved these changes, later dismissed

2022-06-23 13:16 UTC, Patricknshimiyimana submitted a review, later dismissed

2022-06-23 13:50 UTC, Placide123 approved these changes, later dismissed

2022-06-23 14:44 UTC, alaintresor approved these changes, later dismissed

2022-06-24 08:38 UTC, mwisemarierose submitted a review, later dismissed

2022-07-05 09:37 UTC, joshwambere approved these changes

2022-07-05 09:37 UTC, merged