Ft reset password via email 182201722
atlp-rwanda/bravo-bn-be pull request #44
Opened 2022-06-15 17:32 UTC by HiHeritier

**What does this PR do?**

Reset password via Email

**How should this be manually tested?**

- Requesting A Password Reset via `https://<APP_URL>/api/v1/forgot-password`

**Endpoints**

- `POST` - `https://<APP_URL>/api/v1/user/resetpassword` - Used to request for a password reset.
- `PATCH` - `https://<APP_URL>/api/v1/user/resetpassword/{resetToken}` - Accepts the newly assigned password & updates the password in the database.

**What are the relevant pivotal tracker stories?**
https://www.pivotaltracker.com/story/show/182201722

2022-06-16 00:45 UTC, joshwambere requested changes

2022-06-16 00:45 UTC, joshwambere commented on src/controllers/authentication.js
> +        message: 'token send to Email',
can you rerun a message not too technical, average user wont know what's a token

2022-06-16 00:45 UTC, joshwambere commented on src/controllers/authentication.js
> +        console.log(err)
Remove this console

2022-06-16 00:45 UTC, joshwambere commented on src/controllers/authentication.js
> +
this section needs some linting

2022-06-16 00:45 UTC, joshwambere commented on src/helpers/validation_schema.js
> +    phoneNumber: Joi.string().regex(/^[0-9]{10}$/).messages({'string.pattern.base': `Phone number must have 10 digits.`}),
why did you remove required on phoneNumber field

2022-06-16 00:46 UTC, joshwambere commented
and test on your branch are failing you might want check why

2022-06-24 12:43 UTC, Patricknshimiyimana submitted a review, later dismissed
Looks good to me

2022-06-27 09:48 UTC, joshwambere requested changes

2022-06-27 09:48 UTC, joshwambere commented on src/controllers/authentication.js
> +        console.log(err)
delete this console

2022-06-27 09:48 UTC, joshwambere commented on src/routers/api/users.js
> +userRouter.patch('/resetpassword/:token',resetPassword)
can you add some middleware to check new password validity before

2022-07-07 15:49 UTC, mwisemarierose approved these changes, later dismissed

2022-07-12 09:51 UTC, closed without merging