feat(likes):like/unlike an accommodation facility
atlp-rwanda/bravo-bn-be pull request #45
Opened 2022-06-16 17:39 UTC by alaintresor

#### What does this PR do?
like or unlike an accommodation facility

#### Description of Task to be completed?

- like an accommodation
- unlike an accommodation
- get all an accommodation likes

#### How should this be manually tested?
After running the app with` npm run start:dev` and  use this endpoint `/api/v1/accommodation/like/[ACCOMMODATION ID]` on a PUT request to Like or Unlike accommodation or GET `/api/v1/accommodation/like/[ACCOMMODATION ID] ` to view all trip requests
OR
after starting a server, you can open any web browser and put this URL `localhost:[YOUR PORT]/api/v1/docs` to test it with swagger
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201728

2022-06-20 13:50 UTC, uwambajeddy approved these changes, later dismissed
LGTM

2022-06-20 14:22 UTC, Patricknshimiyimana requested changes

2022-06-20 14:22 UTC, Patricknshimiyimana commented on src/controllers/accommodation.controller.js
> +	console.log(userId);
You may wanna remove this console.log

2022-06-20 14:22 UTC, Patricknshimiyimana commented on src/controllers/accommodation.controller.js
> +			console.log(like.dataValues.like);
And this one too

2022-06-20 16:50 UTC, mwisemarierose approved these changes, later dismissed

2022-06-21 10:26 UTC, Patricknshimiyimana submitted a review, later dismissed

2022-06-21 13:00 UTC, joshwambere requested changes

2022-06-21 13:00 UTC, joshwambere commented on src/controllers/accommodation.controller.js
> +import db from '../database/models/index.js';
can you follow the naming the team is using (camel case)

2022-06-21 13:00 UTC, joshwambere commented on src/controllers/accommodation.controller.js
> +		if (like) {
linting needed here

2022-06-21 13:00 UTC, joshwambere commented on src/controllers/accommodation.controller.js
> +				res.status(200).json({ message: 'Like added' });
may return `accommodation liked`

2022-07-12 13:36 UTC, uwambajeddy submitted a review, later dismissed

2022-07-13 11:40 UTC, Placide123 requested changes
Hi, I did the test but you have to put the limitation not all people can do like/unlike for example like and unlike to a manager or travel admin role is not needed, what I think only client who requested the accommodation can like/unlike. Thanks.

2022-07-13 14:05 UTC, Placide123 submitted a review, later dismissed

2022-07-13 14:56 UTC, uwambajeddy submitted a review, later dismissed

2022-07-14 09:18 UTC, joshwambere requested changes, later dismissed

2022-07-14 09:18 UTC, joshwambere commented on src/database/models/useraccommodation.js
> +import { Model } from 'sequelize';
can you name this model to make more sense may be likes or something

2022-07-17 11:37 UTC, Patricknshimiyimana approved these changes

2022-07-17 11:38 UTC, Patricknshimiyimana approved these changes

2022-07-17 13:15 UTC, Placide123 approved these changes

2022-07-18 10:55 UTC, merged