Chore/#182201658 setup project environment
atlp-rwanda/bravo-bn-be pull request #5
Opened 2022-05-22 21:40 UTC by mwisemarierose

#### What does this PR do?
this PR is created so that all folder that will be needed in project  is visible

#### What are the relevant pivotal tracker stories?
Set up an empty Express Boilerplate with dotenv #182201658

2022-05-23 06:09 UTC, Placide123 submitted a review, later dismissed

2022-05-23 08:00 UTC, alaintresor approved these changes, later dismissed

2022-05-23 09:08 UTC, joshwambere requested changes
@mwisemarierose  controllers folder is missing the same applies to routes and test folders

2022-05-23 09:50 UTC, semy-tuyi approved these changes

2022-05-23 09:51 UTC, semy-tuyi approved these changes, later dismissed

2022-05-25 15:17 UTC, uwambajeddy submitted a review, later dismissed
LGTM

2022-05-26 08:29 UTC, didasmbalanya requested changes

2022-05-26 08:29 UTC, didasmbalanya commented on .gitignore
> +.husky
Do not ignore the .husky file. its important

2022-05-26 08:29 UTC, didasmbalanya commented on src/app.js
> +import '@babel/polyfill';
move to first line of the file

2022-05-26 08:29 UTC, didasmbalanya commented on src/app.js
> +app.use(express.static(`${__dirname}/public`));
remove, we will not be serving any static files for now

2022-05-27 18:55 UTC, uwambajeddy submitted a review, later dismissed
LGTM

2022-05-28 11:00 UTC, joshwambere commented on new.json
> +{
@mwisemarierose what is the purpose of this file

2022-05-29 18:04 UTC, joshwambere submitted a review, later dismissed

2022-05-30 08:08 UTC, uwambajeddy submitted a review, later dismissed

2022-05-31 14:28 UTC, joshwambere approved these changes

2022-05-31 14:31 UTC, merged