bug fix login
atlp-rwanda/bravo-bn-be pull request #51
Opened 2022-06-28 11:29 UTC by alaintresor

#### What does this PR do?
update login functionality

#### Description of Task to be completed?
- login a user who is verified

#### How should this be manually tested?
clone this repository
install packages
start server and use swagger to login
#### What are the relevant pivotal tracker stories?

2022-06-29 13:10 UTC, didasmbalanya requested changes

2022-06-29 13:10 UTC, didasmbalanya commented on src/controllers/authentication.js
> +  }
remove this. You can just access the verification token from redis in the test env and use it to test. Or where ever it is stored

2022-06-29 13:10 UTC, didasmbalanya commented on test/userProfile.test.js
> +            expect(res.status).to.equal(200);
test data as well not just status code

2022-06-30 13:39 UTC, semy-tuyi requested changes
user should get verification email after signing up (there is no verification email)

2022-07-07 14:15 UTC, uwambajeddy submitted a review, later dismissed
LGTM

2022-07-07 16:36 UTC, Placide123 submitted a review, later dismissed

2022-07-07 22:56 UTC, joshwambere approved these changes

2022-07-07 22:57 UTC, merged