#182201724 feature trip request endpoints
atlp-rwanda/bravo-bn-be pull request #53
Opened 2022-07-03 20:08 UTC by uwambajeddy

**What does this PR do ?**
CRUD on trip request end points
**Description of Task to be completed**
have the following endpoints working
`POST` `/api/v1/user/trip`
`GET` `/api/v1/user/trip/get`
`GET` `/api/v1/user/trip/get/<trip_id>`
`PATCH` `/api/v1/user/trip/update/<trip_id>`
`DELETE` `/api/v1/user/trip/<trip_id>`
`Swagger document` `[server]/api/v1/doc`

**How should this be manually tested?**

- clone this repository
- checkout to this ft-trip-request-management-182201724
- run npm install to install dependencies
- use post man to test end points

**Relevant Pivotal tracker story**
https://www.pivotaltracker.com/n/projects/2569105

**Trip Request model**
<img width="438" alt="Screen Shot 2022-06-23 at 08 51 34" src="https://user-images.githubusercontent.com/92625609/175235044-c54d87e3-a064-454c-a85b-a5b7c2018322.png">

Reviewers
[@uwambajeddy](https://github.com/uwambajeddy), 
[@johnson](https://stackup-workspace.slack.com/team/U016EN9BVEE)
, [@Patricknshimiyimana](https://github.com/Patricknshimiyimana), 
[@Placide123](https://github.com/Placide123), 
[@mwisemarierose](https://github.com/mwisemarierose)

2022-07-05 07:14 UTC, Placide123 approved these changes, later dismissed

2022-07-05 07:47 UTC, semy-tuyi approved these changes, later dismissed

2022-07-05 09:57 UTC, joshwambere requested changes
When you create trip request and provide unavailable location it return 404 but save the trip request anyway

2022-07-05 17:18 UTC, semy-tuyi approved these changes, later dismissed

2022-07-05 17:21 UTC, Placide123 approved these changes, later dismissed

2022-07-06 17:23 UTC, Patricknshimiyimana approved these changes, later dismissed
LGTM

2022-07-06 19:06 UTC, alaintresor approved these changes, later dismissed

2022-07-07 09:42 UTC, semy-tuyi approved these changes, later dismissed

2022-07-07 09:54 UTC, Placide123 submitted a review, later dismissed

2022-07-07 10:18 UTC, alaintresor approved these changes, later dismissed

2022-07-07 15:21 UTC, Patricknshimiyimana approved these changes, later dismissed

2022-07-07 21:15 UTC, merged