Bug fix reset password via email 182201722
atlp-rwanda/bravo-bn-be pull request #55
Opened 2022-07-08 12:52 UTC by HiHeritier

2022-07-08 14:05 UTC, Placide123 reviewed
on my side, it provides a reset message but the token provided is not helping to reset the password (it is providing `Token is invalid or has expired ), others can test. if it works the problem will be at my end; if not you will make some changes to let it works.

2022-07-08 14:46 UTC, semy-tuyi reviewed
<img width="671" alt="Screen Shot 2022-07-08 at 16 39 45" src="https://user-images.githubusercontent.com/92625609/178014859-566b807d-8f2a-47ec-baae-416528b22e72.png">
try to figure out why swagger is giving that error.
I am getting error "invalid time stamp" when I try to `POST` `api/v1/user/forgotpassowrd`
<img width="537" alt="Screen Shot 2022-07-08 at 16 39 22" src="https://user-images.githubusercontent.com/92625609/178015386-15837d84-9299-4834-a421-33bed8e4f88d.png">

2022-07-13 08:39 UTC, Placide123 approved these changes, later dismissed

2022-07-13 08:40 UTC, uwambajeddy approved these changes, later dismissed

2022-07-15 12:56 UTC, semy-tuyi requested changes
fix this on your swagger documentation please
<img width="686" alt="Screen Shot 2022-07-15 at 14 51 57" src="https://user-images.githubusercontent.com/92625609/179227245-7dffd5c0-4729-412b-b908-4fd0f02df922.png">
Testing this feature locally I am getting this error.
<img width="530" alt="Screen Shot 2022-07-15 at 14 54 13" src="https://user-images.githubusercontent.com/92625609/179227339-d649cb10-2df8-43a9-b5b0-61a969e58185.png">

2022-07-15 13:11 UTC, uwambajeddy requested changes
can't find reset password end points on swagger

2022-07-15 13:13 UTC, Patricknshimiyimana requested changes
While working on the issues above, you may also rebase on develop and resolve conflicts

2022-07-21 18:51 UTC, Placide123 approved these changes

2022-07-21 18:56 UTC, semy-tuyi approved these changes

2022-07-21 21:02 UTC, alaintresor approved these changes

2022-07-21 22:56 UTC, uwambajeddy approved these changes
LGTM

2022-07-22 06:58 UTC, Patricknshimiyimana approved these changes

2022-07-22 08:54 UTC, mwisemarierose approved these changes

2022-07-22 13:15 UTC, joshwambere requested changes

2022-07-22 13:15 UTC, joshwambere commented on src/routers/api/authentication.js
> -import {
why did you delete those lines

2022-07-22 13:15 UTC, joshwambere commented on src/routers/api/authentication.js
> -authRouter.get('/logout', protect, logout);
and here

2022-07-22 13:15 UTC, joshwambere commented on src/routers/api/users.js
> -userRouter.post('/logout', logout);
why did you delete those lines two

2022-07-22 13:15 UTC, joshwambere commented on test/authentication.test.js
> -describe('User logout', () => {
and those tests?

2022-07-22 13:15 UTC, joshwambere commented on test/tripRequest.test.js
> -        expect(message).to.equal('Your token is invalid or expired');
and why did you delete this line also?

2022-07-22 18:40 UTC, closed without merging