feature#182201737-remember information from travel request
atlp-rwanda/bravo-bn-be pull request #60
Opened 2022-07-10 21:58 UTC by Patricknshimiyimana

#### What does this PR do?
 - update remember info option
 - remember info from travel request
 - use information from previous requests into new requests
#### Description of Task to be completed?
 - add remember_info option field to the user model and migration
 - update remember_info option to true or false
#### How should this be manually tested?
 - clone this repository
 - checkout to this branch `ft-remember-info-from-request-182201737`
 - run `npm install` to install dependencies
 - run migrations and seed using `npm run migrate` and `npm run seed`
 - run `npm run start:dev` to start the development server 
 - use swagger on `localhost:4000/api/v1/docs`
 - use the `/api/v1/user/remember-info` endpoint to update remember info field
 - I. create first travel request
 - ll. create second request without adding some fields like `requester address (leavingFrom)`, `passportName`, `passportNumber` and it will be added automatically from the first travel request
#### What are the relevant pivotal tracker stories?
 - https://www.pivotaltracker.com/n/projects/2569105/stories/182201737
#### Screenshots(If appropriate)

2022-07-12 13:30 UTC, uwambajeddy submitted a review, later dismissed

2022-07-12 14:57 UTC, HiHeritier approved these changes, later dismissed

2022-07-18 12:15 UTC, uwambajeddy requested changes
I don't why but this is what I am getting when I try to remove `leavingFrom` from the request fields.
![image](https://user-images.githubusercontent.com/59047760/179509057-8509995f-b990-4004-8e07-9c4eb219b327.png)
Hi @uwambajeddy please don't remove `leavingFrom` we are not getting `leavingFrom` data anymore because this change often, for example if you create a request and want to return you are not leaving from the same place as before.
So the only profile information we are getting from the request are `passportName` and `passportNumber` because they don't change often.

2022-07-18 14:18 UTC, Patricknshimiyimana commented
> I don't why but this is what I am getting when I try to remove `leavingFrom` from the request fields. ![image](https://user-images.githubusercontent.com/59047760/179509057-8509995f-b990-4004-8e07-9c4eb219b327.png)

Hi @uwambajeddy please don't remove `leavingFrom` we are not getting `leavingFrom` data anymore because this change often, for example if you create a request and want to return you are not leaving from the same place as before.
So the only profile information we are getting from the request are `passportName` and `passportNumber` because they don't change often.

And don't remove them just leave them empty like this `passportName: ""`, passportNumber: ""`

2022-07-18 15:38 UTC, Patricknshimiyimana commented
> Hi @uwambajeddy please don't remove `leavingFrom` we are not getting `leavingFrom` data anymore because this change often, for example if you create a request and want to return you are not leaving from the same place as before. So the only profile information we are getting from the request are `passportName` and `passportNumber` because they don't change often.
> 
> And don't remove them, just leave them empty like this `passportName: ""`, `passportNumber: ""`

May you approve if you found it working

2022-07-19 06:39 UTC, uwambajeddy requested changes
I tried to remigrate but this error still poping up
![image](https://user-images.githubusercontent.com/59047760/179682889-b5e1f6bd-a730-44b3-a687-5d9c7b1ddd28.png)

2022-07-20 14:16 UTC, Placide123 submitted a review, later dismissed

2022-07-20 16:42 UTC, alaintresor submitted a review, later dismissed

2022-07-21 06:55 UTC, uwambajeddy submitted a review, later dismissed
LGTM

2022-07-22 09:18 UTC, merged