Ft rate accommodation 182201730
atlp-rwanda/bravo-bn-be pull request #66
Opened 2022-07-15 09:26 UTC by mwisemarierose

2022-07-19 14:59 UTC, Placide123 submitted a review, later dismissed

2022-07-19 19:03 UTC, alaintresor submitted a review, later dismissed

2022-07-22 12:49 UTC, joshwambere requested changes

2022-07-22 12:49 UTC, joshwambere commented on src/controllers/rates.controller.js
> +  console.log(isItRated);
delete this console

2022-07-22 12:49 UTC, joshwambere commented on src/controllers/rates.controller.js
> +export const createRate = catchAsync(async (req, res, next) => {
and please add and endpoint to get all ratings for one accommodation

2022-07-25 07:31 UTC, uwambajeddy requested changes

2022-07-25 07:31 UTC, uwambajeddy commented on src/controllers/rates.controller.js
> +      new AppError('Sorry, trip request must be approved to proceed ', 401),
this logic means that if I have many trip requests, all of them must be approved to rate a single accommodation. And that I guess should not be the scenario.

2022-07-25 07:36 UTC, uwambajeddy requested changes
I tried to update the rates but they remained the same
![Screenshot (429)](https://user-images.githubusercontent.com/59047760/180723219-e177539a-d541-40e4-9c92-61b89b5530a4.png)

2022-07-27 09:59 UTC, closed without merging