create search functionality
atlp-rwanda/bravo-bn-be pull request #68
Opened 2022-07-18 11:26 UTC by Placide123

2022-07-26 10:55 UTC, HiHeritier approved these changes, later dismissed

2022-07-27 17:04 UTC, HiHeritier requested changes, later dismissed
Everything works as required but make sure that you increase your coverage

2022-07-28 14:58 UTC, HiHeritier approved these changes
Looks good

2022-07-28 15:06 UTC, Patricknshimiyimana approved these changes

2022-07-29 08:06 UTC, merged