ft(reset password)
atlp-rwanda/bravo-bn-be pull request #71
Opened 2022-07-22 18:33 UTC by HiHeritier

**What does this PR do?**

feature to reset password

**Description of Task to be completed?**

- User can be able to reset password

**How should this be manually tested?**

- Clone the repo checkout to branch `reset-password-182201722`
- Run `npm install` to install modules
- Run `npm run start:prod` to start the production server
- In your API testing tool (postman recommended ) call api `/api/v1/user/forgotpassword` to have the token to reset password sent to your email
-Copy the token sent to your email then call api `/api/v1/user/resetpassword/$token`  to inter new password

**What are the relevant pivotal tracker stories?**
https://www.pivotaltracker.com/story/show/182201722

**Screenshots**
![Screenshot (196)](https://user-images.githubusercontent.com/95864845/175346286-e607fc91-2847-46d5-a8b2-f159854393e3.png)

![Screenshot (197)](https://user-images.githubusercontent.com/95864845/175346370-81e10659-00f0-416c-9171-af99be8996e0.png)

![Screenshot (198)](https://user-images.githubusercontent.com/95864845/175346445-d09505ec-0afb-4a5d-b90b-db3bfa32f151.png)

2022-07-23 21:57 UTC, Placide123 requested changes
please , check your endpoint which make a rest of password try to make it works and tell us we check again.

2022-07-25 07:55 UTC, uwambajeddy requested changes
I encountered this error trying to run the app
![Screenshot (431)](https://user-images.githubusercontent.com/59047760/180726775-ae0a80fa-89cc-4cb6-a94a-8377a48bbf7b.png)

2022-07-25 18:57 UTC, Placide123 requested changes
the endpoint of changing password is not working, my request is running infinitely. try to fix it and let us know when it is solved.

2022-07-26 09:55 UTC, Patricknshimiyimana approved these changes

2022-07-26 09:59 UTC, Placide123 approved these changes

2022-07-26 10:00 UTC, alaintresor approved these changes

2022-07-26 10:41 UTC, joshwambere approved these changes

2022-07-26 10:42 UTC, merged