ft(rate):rate accomodation centre
atlp-rwanda/bravo-bn-be pull request #72
Opened 2022-07-27 19:19 UTC by mwisemarierose

What does this PR do?
Users should be able to rate accomodation centre

Description of Task to be completed?
rate accomodation centre

How should this be manually tested?
clone this repository
checkout to this branch ft-rate-accommodation-182201730
run npm install to install dependencies
run migrations using npm run migrate
run npm run start:dev to start the development server
add a tripRequest: '/api/v1//user/trip
approve the tripRequest : /api/v1/user/trip/approve/${requestId}
wait for 24hrs to rate the accomodation
rate accomodation: 'api/v1/rates/createRate'

What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2569105

2022-07-28 07:41 UTC, Placide123 approved these changes, later dismissed

2022-07-28 08:09 UTC, Placide123 submitted a review, later dismissed

2022-07-28 08:40 UTC, uwambajeddy submitted a review, later dismissed

2022-07-28 10:21 UTC, joshwambere requested changes

2022-07-28 10:21 UTC, joshwambere commented on src/controllers/rates.controller.js
> +      return res.status(200).json({
can you also return number ratings (counts)

2022-07-28 10:21 UTC, joshwambere commented on src/controllers/rates.controller.js
> +      data: updateRate,
it's not returning right data and right status cod2
![Screenshot from 2022-07-28 12-04-29](https://user-images.githubusercontent.com/59834399/181482178-527c14fb-775d-4a23-807f-08bdd20cd1b0.png)

2022-07-29 08:15 UTC, joshwambere requested changes

2022-07-29 08:15 UTC, joshwambere commented on src/controllers/rates.controller.js
> +      data: rates,
you should return the whole object of ratings not the actual value the user provided

2022-07-29 14:33 UTC, Placide123 approved these changes

2022-07-29 14:58 UTC, alaintresor approved these changes

2022-08-04 14:29 UTC, joshwambere approved these changes

2022-08-04 14:30 UTC, merged